### ISSUE TITLE
Arvan CDN

### ISSUE THREAD

**Issue by SORENCO** [amircloner/tcp-vpn-proxy#1]
When enable Cloud Service on record, the proxy doesn't work and I have this error on client side: ''unable to parse TLS packet header"
But when disable Cloud Service, everything work fine, but i don't khow this work on intranet in iran.

I set http connection with 80 port between cdn and origin server.

**Comment by amircloner** [comment]
Please send more information like screenshot or log data
And Be sure Arvan SSL like this image

![Uploading screencapture-panel-arvancloud-f98EDkV9sKPtaPx9WcJHwm-cdn-generace-ir-https-2022-10-13-19_02_31.png…]()

**Comment by SORENCO** [comment]
thanks
what about these setting
Are these set correctly?
![Screenshot 2022-10-13 191659](https://user-images.githubusercontent.com/104919399/195647161-9c6dcc9f-66f4-4157-8a54-1ec39b033b03.png)
![Screenshot 2022-10-13 191747](https://user-images.githubusercontent.com/104919399/195647174-fc4117dd-3572-467d-a688-cb8a42a2f4c5.png)

**Comment by SORENCO** [comment]
I’m so grateful

**Comment by k90mirzaei** [comment]
based upon this [link](https://gist.github.com/k90mirzaei/50a95db91b001ff73eb957db16239554), It works fine when I use the foreign server, but it becomes a little bit insane when I want to use the Iran server. I used the config you suggested here, but it did not work.

**Comment by amircloner** [comment]
You want to
use two server (Enternal and External) instead of External server and CDN

**Comment by k90mirzaei** [comment]
No bro, I've just implemented an external server and want to use CDN

**Comment by wulfric93** [comment]
hi there 
i set everything and still cant use arvan cdn 
my domain is "ml"
but i couldnt be able to set up 
how should i configure arvan to use its cdn ?
